CREATE TABLE User
(
	ID INT NOT NULL PRIMARY KEY,
	USERNAME VARCHAR (20) NOT NULL,
	PASSWORD VARCHAR (8) NOT NULL,
    	FULLNAME VARCHAR (40) NOT NULL,
        	EMAIL VARCHAR (20) NOT NULL,
        	PHONENUMBER VARCHAR (9) NOT NULL,
            USERTYPE VARCHAR (12) NOT NULL
);
CREATE TABLE Book
(
	ID INT NOT NULL PRIMARY KEY,
	TITLE VARCHAR (30) NOT NULL,
	AUTHOR VARCHAR (30) NOT NULL,
    	COPIES VARCHAR (30) NOT NULL
);
CREATE TABLE BookRecord
(
	ID INT NOT NULL PRIMARY KEY,
	CUSTOMER INT NOT NULL,
	BOOK INT NOT NULL,
	ISSUEDDATE Date NOT NULL,
	EXPECTEDRETURN DATE NOT NULL
);
